### ISSUE TITLE
tgkill's occuring

### ISSUE THREAD

**Issue by securit** [yozef/FusedLocation#4]
Nice work here! 
Unfortunately I'm having a wee problem. I'm not sure where to go with this one.... 
```
backtrace:
  native: pc 0000000000042744  /system/lib/libc.so (tgkill+12)
  native: pc 0000000000040351  /system/lib/libc.so (pthread_kill+32)
  native: pc 000000000001ca8b  /system/lib/libc.so (raise+10)
  native: pc 0000000000019d09  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 000000000001754c  /system/lib/libc.so (abort+4)
  native: pc 0000000000334105  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+228)
  native: pc 00000000000f476b  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+2226)
  native: pc 000000000025b635  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1552)
  native: pc 000000000025ba63  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+74)
  native: pc 0000000000295bb9  /system/lib/libart.so (_ZN3art3JNI15CallVoidMethodAEP7_JNIEnvP8_jobjectP10_jmethodIDP6jvalue+472)
  native: pc 0000000000003b7d  /data/app/com.my.tracker-2/lib/arm/libca.underlabs.fusedlocation.so (_ZN2ca9underlabs13fusedlocation19FusedlocationModule16startGeoLocationERKN2v820FunctionCallbackInfoINS3_5ValueEEE+268)
  native: pc 00000000003bba1c  /data/app/com.my.tracker-2/lib/arm/libkroll-v8.so (_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+136)
  native: pc 000000000040c424  /data/app/com.my.tracker-2/lib/arm/libkroll-v8.so
  native: pc 000000000040ca94  /data/app/com.my.tracker-2/lib/arm/libkroll-v8.so
  native: pc 0000000000000098  <unknown>
```

This was running on Galaxy devices. So far all have been on Android 6.0, about two thirds on a S6  and the remainder on an A5.

```
Android version
Android 6.0
Device
Galaxy S6 (zeroflte)
Manufacturer Samsung 
RAM (MB) 3072
 Screen size 1440 × 2560 
Screen density (dpi) 640 
Native platform armeabi-v7a 
OpenGL ES version 3.1 
CPU make Samsung 
CPU model Exynos 7420
```

**Comment by yozef** [comment]
If you are using Ti's Map module, make sure to delete in FusedLocation's folder .../1.2.2/lib/ these 2 jars:
- classes-base.jar and
- classes-basement.jar

Since they’re already in ti.map, and just leave classes.jar (which holds com.google.android.gms.location)

**Comment by securit** [comment]
Thanks for your quick reply. I have already removed these files. All I have in my modules/android/ca.underlabsl.fusedlocation/1.2.3/lib directories are
```
classes.jar
README
version
```

**Comment by yozef** [comment]
Which Ti SDK version are you using?

**Comment by securit** [comment]
6.1.0 although I'm in the process of testing in 6.1.1

**Comment by securit** [comment]
Hi Joseph, did you get any further with these tgkills? I had 23 of them occur yesterday alone.

**Comment by yozef** [comment]
none, it's running well on my end.

**Comment by securit** [comment]
OK, well I might try recompiling with 6.1.1-GA and rolling that out then to see if it helps.

Any idea what Gary’s timeframes are on adding fused location to the Ti SDK?

Thanks
Greg

**Comment by securit** [comment]
OK, I redistributed with a build based on 6.1.1.GA and am still getting the tgkill errors"
```
backtrace:
  native: pc 000000000004a230  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000479c3  /system/lib/libc.so (pthread_kill+34)
  native: pc 000000000001d9c5  /system/lib/libc.so (raise+10)
  native: pc 0000000000019511  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 0000000000017150  /system/lib/libc.so (abort+4)
  native: pc 000000000031b3bd  /system/lib/libart.so (_ZN3art7Runtime5AbortEv+252)
  native: pc 00000000000b4ccb  /system/lib/libart.so (_ZN3art10LogMessageD2Ev+866)
  native: pc 000000000023a169  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1584)
  native: pc 000000000023a433  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
  native: pc 000000000026b089  /system/lib/libart.so (_ZN3art3JNI15CallVoidMethodAEP7_JNIEnvP8_jobjectP10_jmethodIDP6jvalue+488)
  native: pc 0000000000003b7d  /data/app/com.snapithd.mobilevms-2/lib/arm/libca.underlabs.fusedlocation.so (_ZN2ca9underlabs13fusedlocation19FusedlocationModule16startGeoLocationERKN2v820FunctionCallbackInfoINS3_5ValueEEE+268)
  native: pc 00000000003bc014  /data/app/com.snapithd.mobilevms-2/lib/arm/libkroll-v8.so (_ZN2v88internal25FunctionCallbackArguments4CallEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEE+136)
  native: pc 000000000040ca1c  /data/app/com.snapithd.mobilevms-2/lib/arm/libkroll-v8.so
  native: pc 000000000040d08c  /data/app/com.snapithd.mobilevms-2/lib/arm/libkroll-v8.so
  native: pc 0000000000000098  <anonymous:58e0a000>
```
